apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-db
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: 'registry.redhat.io/rhel8/postgresql-96:latest'