apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
spec:
  template:
    spec:
      containers:
        - name: trino-coordinator
          image: 'quay.io/opendatahub/trino:355'