---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
    password-authenticator.name=file
    file.password-file=/tmp/password.db
    access-control.name=file
    security.config-file=etc/trino/rules.json
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  password.db: |-
    test:$2y$10$TaxJTmcylJEhfhy8leh/Pe22IVqaPiwNuJ56s9TNHIFhV0z81z6Qu
    test2:$2y$10$TaxJTmcylJEhfhy8leh/Pe22IVqaPiwNuJ56s9TNHIFhV0z81z6Qu
  rules.json: |
    {
      "catalogs": [
        {
          "user": "test",
          "catalog": "system",
          "allow": true
        },
        {
          "catalog": "hive",
          "allow": true
        },
        {
          "user": "test|test2",
          "catalog": "postgresql",
          "allow": true
        },
        {
          "catalog": "system",
          "allow": false
        }
                  ]
      }
    

#  $touch password.db
#  $htpasswd -B -C 10 password.db test