apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  template:
    spec:
      initContainers:
      - name: superset-init
#        image: quay.io/internaldatahub/superset:1.3.0
        image: quay.io/opendatahub/superset:1.4.1-ubi
      containers:
      - name: superset
        # image: quay.io/internaldatahub/superset:1.1.0
#        image: quay.io/internaldatahub/superset:1.3.0
        image: quay.io/opendatahub/superset:1.4.1-ubi